CREATE OR REPLACE PROCEDURE "PC_PRODUCTS_UPDATE"(
	P_ID TBL_PRODUCT.ID%TYPE,
	P_PRODUCT_CODE TBL_PRODUCT.PRODUCT_CODE%TYPE,
	P_PRODUCT_NAME TBL_PRODUCT.PRODUCT_NAME%TYPE,
	P_PRODUCT_TYPE TBL_PRODUCT.PRODUCT_TYPE%TYPE,
	P_PRODUCT_DESC TBL_PRODUCT.PRODUCT_DESC%TYPE,
	P_INT_PAYMENT_UNIT TBL_PRODUCT.INT_PAYMENT_UNIT%TYPE,
	P_INT_PAYMENT_FREQUENCY TBL_PRODUCT.INT_PAYMENT_FREQUENCY%TYPE,
	P_PRICIPAL_PAYMENT_UNIT TBL_PRODUCT.PRICIPAL_PAYMENT_UNIT%TYPE,
	P_PRICIPAL_PAYMENT_FREQUENCY TBL_PRODUCT.PRICIPAL_PAYMENT_FREQUENCY%TYPE,
	P_RECORD_STAT TBL_PRODUCT.RECORD_STAT%TYPE,
	P_PRODUCT_TYPE_ID TBL_PRODUCT.PRODUCT_TYPE_ID%TYPE,
	P_MAKER_ID TBL_PRODUCT.MAKER_ID%TYPE,
	P_TRN_CODE TBL_PRODUCT.TRN_CODE%TYPE,
	P_GL_CODE TBL_PRODUCT.GL_CODE%TYPE,
	P_ROW OUT NUMBER
) AS
	V_CLOSE_DATE DATE := NULL;
	V_CLOSE_USER_ID VARCHAR2(50) := NULL;
BEGIN
	IF P_RECORD_STAT = 'C' THEN
		V_CLOSE_DATE := SYSDATE;
		V_CLOSE_USER_ID := P_MAKER_ID;
	END IF;

	UPDATE TBL_PRODUCT SET 
	PRODUCT_CODE=P_PRODUCT_CODE,
	PRODUCT_NAME=P_PRODUCT_NAME,
	PRODUCT_TYPE=P_PRODUCT_TYPE,
	PRODUCT_DESC=P_PRODUCT_DESC,
	INT_PAYMENT_UNIT=P_INT_PAYMENT_UNIT,
	INT_PAYMENT_FREQUENCY=P_INT_PAYMENT_FREQUENCY,
	PRICIPAL_PAYMENT_UNIT=P_PRICIPAL_PAYMENT_UNIT,
	PRICIPAL_PAYMENT_FREQUENCY=P_PRICIPAL_PAYMENT_FREQUENCY,
	RECORD_STAT=P_RECORD_STAT,
	PRODUCT_TYPE_ID=P_PRODUCT_TYPE_ID,
	TRN_CODE = P_TRN_CODE,
	GL_CODE = P_GL_CODE,
	MAKER_ID=P_MAKER_ID
	WHERE ID=P_ID;
	
	P_ROW := SQL%ROWCOUNT;
END;




CREATE OR REPLACE PROCEDURE "PC_PRODUCT_TYPE_UPDATE"(
	P_ID TBL_PRODUCT_TYPE.ID%TYPE,
	P_PRODUCT_TYPE_NAME TBL_PRODUCT_TYPE.PRODUCT_TYPE_NAME%TYPE,
	P_PRODUCT_TYPE_DESC TBL_PRODUCT_TYPE.PRODUCT_TYPE_DESC%TYPE,
	P_RECORD_STAT TBL_PRODUCT_TYPE.RECORD_STAT%TYPE,
	P_USER_ID TBL_PRODUCT_TYPE.CLOSE_USER_ID%TYPE,P_ROW OUT NUMBER) 
	AS
	V_CLOSE_DATE DATE := NULL;
	V_CLOSE_USER_ID VARCHAR2(50) := NULL;
	
BEGIN
	IF P_RECORD_STAT = 'C' THEN
		V_CLOSE_DATE := SYSDATE;
		V_CLOSE_USER_ID := P_USER_ID;
	END IF;

	UPDATE TBL_PRODUCT_TYPE 
	SET 
	PRODUCT_TYPE_NAME=P_PRODUCT_TYPE_NAME,
	PRODUCT_TYPE_DESC=P_PRODUCT_TYPE_DESC,
	RECORD_STAT=P_RECORD_STAT,
	CLOSE_DATE=V_CLOSE_DATE,
	CLOSE_USER_ID=V_CLOSE_USER_ID 
	WHERE ID=P_ID;

	P_ROW := SQL%ROWCOUNT;
END PC_PRODUCT_TYPE_UPDATE;