
CREATE OR REPLACE PROCEDURE "PC_PRODUCT_CREATE"
(
          P_PRODUCT_TYPE_ID TBL_PRODUCT.PRODUCT_TYPE_ID%TYPE,
          P_CLOSE_DATE TBL_PRODUCT.CLOSE_DATE%TYPE,
          P_CLOSE_USER_ID TBL_PRODUCT.CLOSE_USER_ID%TYPE,
          P_GL_CODE TBL_PRODUCT.GL_CODE%TYPE,
          P_MAKER_ID TBL_PRODUCT.MAKER_ID%TYPE,
          P_TRN_CODE TBL_PRODUCT.TRN_CODE%TYPE,
          P_PRODUCT_CODE TBL_PRODUCT.PRODUCT_CODE%TYPE,
          P_PRODUCT_NAME TBL_PRODUCT.PRODUCT_NAME%TYPE,
          P_PRODUCT_TYPE TBL_PRODUCT.PRODUCT_TYPE%TYPE,
          P_PRODUCT_DESC TBL_PRODUCT.PRODUCT_DESC%TYPE,
          P_INT_PAYMENT_UNIT TBL_PRODUCT.INT_PAYMENT_UNIT%TYPE,
          P_INT_PAYMENT_FREQUENCY TBL_PRODUCT.INT_PAYMENT_FREQUENCY%TYPE,
          P_PRICIPAL_PAYMENT_UNIT TBL_PRODUCT.PRICIPAL_PAYMENT_UNIT%TYPE,
          P_PRICIPAL_PAYMENT_FREQUENCY TBL_PRODUCT.PRICIPAL_PAYMENT_FREQUENCY%TYPE,
          P_CREATE_DATE TBL_PRODUCT.CREATE_DATE%TYPE,
          P_RECORD_STAT TBL_PRODUCT.RECORD_STAT%TYPE
)
AS
    V_ID NUMBER(10);
BEGIN
    V_ID := FN_GET_MAX_ID('TBL_PRODUCT'); 
INSERT INTO TBL_PRODUCT(
        PRODUCT_TYPE_ID,
         CLOSE_DATE,
         CLOSE_USER_ID,
         GL_CODE,
         MAKER_ID,
         TRN_CODE,
         ID,
         PRODUCT_CODE,
         PRODUCT_NAME,
         PRODUCT_TYPE,
         PRODUCT_DESC,
         INT_PAYMENT_UNIT,
         INT_PAYMENT_FREQUENCY,
         PRICIPAL_PAYMENT_UNIT,
         PRICIPAL_PAYMENT_FREQUENCY,
         CREATE_DATE,
         RECORD_STAT
)
VALUES
(
          P_PRODUCT_TYPE_ID,
          P_CLOSE_DATE,
          P_CLOSE_USER_ID,
          P_GL_CODE,
          P_MAKER_ID,
          P_TRN_CODE,
		  V_ID,
          P_PRODUCT_CODE,
          P_PRODUCT_NAME,
          P_PRODUCT_TYPE,
          P_PRODUCT_DESC,
          P_INT_PAYMENT_UNIT,
          P_INT_PAYMENT_FREQUENCY,
          P_PRICIPAL_PAYMENT_UNIT,
          P_PRICIPAL_PAYMENT_FREQUENCY,
          P_CREATE_DATE,
          P_RECORD_STAT
)
END;
